### ISSUE TITLE
获取 token 的请求方法应该改为 post 而非 request

### ISSUE THREAD

**Issue by 1421393078** [zmoyi/JsTan#1]
getInitToken, getAccessToken 应该调用 $this->post 而不是 $this->request。
因为 $this->request 会把 $data 数据转到 $param['biz'] 中, 从而出错, 请修复

**Comment by zmoyi** [comment]
您测试一下，如果有错误可以提个pr的

**Comment by zmoyi** [comment]
您好，我没有密钥，所以这里您能帮忙修复一下嘛

**Comment by zmoyi** [comment]
> getInitToken, getAccessToken 应该调用 $this->post 而不是 $this->request。 因为 $this->request 会把 $data 数据转到 $param['biz'] 中，因此出错，请修复

您好，我没有密钥，你能帮忙修复一下嘛，麻烦您提一个pr
